general:
  # When running in auto mode set the poll interval to x seconds.
  # Defaults to 5 seconds.
  poll_interval: 5

  # Some processors are using the Package prefix others the Physical prefix.
  # For example: Package id 0. If the sensors command return anything different
  # than Package of Physical you can set this setting to that prefix.
  # When using this setting, the highest temperature is returned from values
  # that match the coretemp_label_prefix setting. When this setting is not being used
  # the highest temperature of either the package or a core is being used as the core temp.
  # You can also set this to a specific core or package. E.g.: Core 0, or: Package id 0.
  coretemp_label_prefix: 'Package'

ipmi:
  # Set authentication parameters. host, username and password 
  # are all optional if none are provided, the application will 
  # assume IPMI is present on the machine it self (localhost).
  host: localhost
  #username: username 
  #password: supersecret

  # Define the fan profiles that are present on your Supermicro
  # motherboard. Check your manual or figure this out with ipmitool.
  # If none are provided this will default to: 
  # profiles:
  #   full: 1
  # Make sure you define at least the 'full' fan profile.
  profiles:
    normal: 0
    full: 1
    optimal: 2
    heavyio: 4

zones:
  # Set the PWM steps for the system zone (FAN1-FAN9).
  # The used format is 'temp: fan speed percentage'. e.g. 30: 50
  # The default fan profile for the system zone is:
  # system:
  #   0: 30
  #   80: 100
  system:
    0: 20
    20: 40
    30: 50
    40: 60
    50: 75
    60: 85
    70: 100

  # Set the PWM steps for the peripheral zone (FANA-FANC).
  # The used format is 'temp: fan speed percentage'. e.g. 30: 40
  # The default fan profile for the peripheral zone is:
  # peripheral:
  #   0: 50
  #   60: 100
  peripheral:
    0: 50
    35: 60
    40: 70
    45: 80
    50: 90
    55: 100